class PHKBCRunner{
	public static void main(String[] nnn){
		Printer printer= new Printer();
		Printer printer1= new Printer("HP");
		Printer printer2= new Printer("Panasonic","InkJet");
		Printer printer3= new Printer("Epson", "Laser", 9500);
		Printer printer4= new Printer("Canon", "Laser",10500, 310);
		Printer printer5= new Printer("Dell", "InkJet",12500, 410, 150);
	
		
	System.out.println(" ");	
	System.out.println("printer brand :"+printer.brand);
	System.out.println("printer type:"+printer.type);
	System.out.println("printer price:"+printer.price);
	System.out.println("printer serialNo:"+printer.serialNo);
	System.out.println("printer noOfPages:"+printer.noOfPages);
	System.out.println(" ");
	System.out.println("printer1 brand :"+printer1.brand);
	System.out.println("printer1 type:"+printer1.type);
	System.out.println("printer1 price:"+printer1.price);
	System.out.println("printer1 serialNo:"+printer1.serialNo);
	System.out.println("printer1 noOfPages:"+printer1.noOfPages);
	System.out.println(" ");
	System.out.println("printer2 brand :"+printer2.brand);
	System.out.println("printer2 type:"+printer2.type);
	System.out.println("printer2 price:"+printer2.price);
	System.out.println("printer2 serialNo:"+printer2.serialNo);
	System.out.println("printer2 noOfPages:"+printer2.noOfPages);
	System.out.println(" ");
	System.out.println("printer3 brand :"+printer3.brand);
	System.out.println("printer3 type:"+printer3.type);
	System.out.println("printer3 price:"+printer3.price);
	System.out.println("printer3 serialNo:"+printer3.serialNo);
	System.out.println("printer3 noOfPages:"+printer3.noOfPages);
	System.out.println(" ");
	System.out.println("printer4 brand :"+printer4.brand);
	System.out.println("printer4 type:"+printer4.type);
	System.out.println("printer4 price:"+printer4.price);
	System.out.println("printer4 serialNo:"+printer4.serialNo);
	System.out.println("printer4 noOfPages:"+printer4.noOfPages);
	System.out.println(" ");
	System.out.println("printer5 brand :"+printer5.brand);
	System.out.println("printer5 type:"+printer5.type);
	System.out.println("printer5 price:"+printer5.price);
	System.out.println("printer5 serialNo:"+printer5.serialNo);
	System.out.println("printer5 noOfPages:"+printer5.noOfPages);
	System.out.println(" ");
	
	
		Helmet helmet= new Helmet();
		Helmet helmet1= new Helmet("Studds");
		Helmet helmet2= new Helmet("Steelbird","Full_Helmet");
		Helmet helmet3= new Helmet("Vega", "Half_Helmet", 900);
		Helmet helmet4= new Helmet("Aerostar", "Full_Helmet",1000, "Non_ISI");
		Helmet helmet5= new Helmet("LS2", "Half_Helmet",1500, "ISI", "Large");
		
	System.out.println(" ");	
	System.out.println("helmet brand :"+helmet.brand);
	System.out.println("helmet type:"+helmet.type);
	System.out.println("helmet price:"+helmet.price);
	System.out.println("helmet quality:"+helmet.quality);
	System.out.println("helmet size:"+helmet.size);
	System.out.println(" ");
	System.out.println("helmet1 brand :"+helmet1.brand);
	System.out.println("helmet1 type:"+helmet1.type);
	System.out.println("helmet1 price:"+helmet1.price);
	System.out.println("helmet1 quality:"+helmet1.quality);
	System.out.println("helmet1 size:"+helmet1.size);
	System.out.println(" ");
	System.out.println("helmet2 brand :"+helmet2.brand);
	System.out.println("helmet2 type:"+helmet2.type);
	System.out.println("helmet2 price:"+helmet2.price);
	System.out.println("helmet2 quality:"+helmet2.quality);
	System.out.println("helmet2 size:"+helmet2.size);
	System.out.println(" ");
	System.out.println("helmet3 brand :"+helmet3.brand);
	System.out.println("helmet3 type:"+helmet3.type);
	System.out.println("helmet3 price:"+helmet3.price);
	System.out.println("helmet3 quality:"+helmet3.quality);
	System.out.println("helmet3 size:"+helmet3.size);
	System.out.println(" ");
	System.out.println("helmet4 brand :"+helmet4.brand);
	System.out.println("helmet4 type:"+helmet4.type);
	System.out.println("helmet4 price:"+helmet4.price);
	System.out.println("helmet4 quality:"+helmet4.quality);
	System.out.println("helmet4 size:"+helmet4.size);
	System.out.println(" ");
	System.out.println("helmet5 brand :"+helmet5.brand);
	System.out.println("helmet5 type:"+helmet5.type);
	System.out.println("helmet5 price:"+helmet5.price);
	System.out.println("helmet5 quality:"+helmet5.quality);
	System.out.println("helmet5 size:"+helmet5.size);
	System.out.println(" ");
	
	
		KeyChain keychain= new KeyChain();
		KeyChain keychain1= new KeyChain(5);
		KeyChain keychain2= new KeyChain(8,"Leather");
		KeyChain keychain3= new KeyChain(7, "Iron", 500);
		KeyChain keychain4= new KeyChain(14, "Silver",21500, "Good");
		KeyChain keychain5= new KeyChain(4, "Copper",150, "Medium", "Golden");
		
	System.out.println(" ");	
	System.out.println("keychain durabilityOfMetalInYears :"+keychain.durabilityOfMetalInYears);
	System.out.println("keychain type:"+keychain.type);
	System.out.println("keychain price:"+keychain.price);
	System.out.println("keychain quality:"+keychain.quality);
	System.out.println("keychain color:"+keychain.color);
	System.out.println(" ");
	System.out.println("keychain1 durabilityOfMetalInYears :"+keychain1.durabilityOfMetalInYears);
	System.out.println("keychain1 type:"+keychain1.type);
	System.out.println("keychain1 price:"+keychain1.price);
	System.out.println("keychain1 quality:"+keychain1.quality);
	System.out.println("keychain1 color:"+keychain1.color);
	System.out.println(" ");
	System.out.println("keychain2 durabilityOfMetalInYears :"+keychain2.durabilityOfMetalInYears);
	System.out.println("keychain2 type:"+keychain2.type);
	System.out.println("keychain2 price:"+keychain2.price);
	System.out.println("keychain2 quality:"+keychain2.quality);
	System.out.println("keychain2 color:"+keychain2.color);
	System.out.println(" ");
	System.out.println("keychain3 durabilityOfMetalInYears :"+keychain3.durabilityOfMetalInYears);
	System.out.println("keychain3 type:"+keychain3.type);
	System.out.println("keychain3 price:"+keychain3.price);
	System.out.println("keychain3 quality:"+keychain3.quality);
	System.out.println("keychain3 color:"+keychain3.color);
	System.out.println(" ");
	System.out.println("keychain4 durabilityOfMetalInYears :"+keychain4.durabilityOfMetalInYears);
	System.out.println("keychain4 type:"+keychain4.type);
	System.out.println("keychain4 price:"+keychain4.price);
	System.out.println("keychain4 quality:"+keychain4.quality);
	System.out.println("keychain4 color:"+keychain4.color);
	System.out.println(" ");
	System.out.println("keychain5 durabilityOfMetalInYears :"+keychain5.durabilityOfMetalInYears);
	System.out.println("keychain5 type:"+keychain5.type);
	System.out.println("keychain5 price:"+keychain5.price);
	System.out.println("keychain5 quality:"+keychain5.quality);
	System.out.println("keychain5 color:"+keychain5.color);
	System.out.println(" ");
	
	
		Bracelet bracelet= new Bracelet();
		Bracelet bracelet1= new Bracelet("Joyalukkas");
		Bracelet bracelet2= new Bracelet("Tanishq","Gold");
		Bracelet bracelet3= new Bracelet("Malabar Gold & Diamonds", "Platinum", 450000);
		Bracelet bracelet4= new Bracelet("Senco Gold & Diamonds", "Diamond",1050000, 24);
		Bracelet bracelet5= new Bracelet("Bank Outlets", "Silver",52500, 22, 18);
		
	System.out.println(" ");	
	System.out.println("bracelet brand :"+bracelet.brand);
	System.out.println("bracelet type:"+bracelet.type);
	System.out.println("bracelet price:"+bracelet.price);
	System.out.println("bracelet qualityInCarat:"+bracelet.qualityInCarat);
	System.out.println("bracelet durabilityOfMetalInYears:"+bracelet.durabilityOfMetalInYears);
	System.out.println(" ");
	System.out.println("bracelet1 brand :"+bracelet1.brand);
	System.out.println("bracelet1 type:"+bracelet1.type);
	System.out.println("bracelet1 price:"+bracelet1.price);
	System.out.println("bracelet1 qualityInCarat:"+bracelet1.qualityInCarat);
	System.out.println("bracelet1 durabilityOfMetalInYears:"+bracelet1.durabilityOfMetalInYears);
	System.out.println(" ");
	System.out.println("bracelet2 brand :"+bracelet2.brand);
	System.out.println("bracelet2 type:"+bracelet2.type);
	System.out.println("bracelet2 price:"+bracelet2.price);
	System.out.println("bracelet2 qualityInCarat:"+bracelet2.qualityInCarat);
	System.out.println("bracelet2 durabilityOfMetalInYears:"+bracelet2.durabilityOfMetalInYears);
	System.out.println(" ");
	System.out.println("bracelet3 brand :"+bracelet3.brand);
	System.out.println("bracelet3 type:"+bracelet3.type);
	System.out.println("bracelet3 price:"+bracelet3.price);
	System.out.println("bracelet3 qualityInCarat:"+bracelet3.qualityInCarat);
	System.out.println("bracelet3 durabilityOfMetalInYears:"+bracelet3.durabilityOfMetalInYears);
	System.out.println(" ");
	System.out.println("bracelet4 brand :"+bracelet4.brand);
	System.out.println("bracelet4 type:"+bracelet4.type);
	System.out.println("bracelet4 price:"+bracelet4.price);
	System.out.println("bracelet4 qualityInCarat:"+bracelet4.qualityInCarat);
	System.out.println("bracelet4 durabilityOfMetalInYears:"+bracelet4.durabilityOfMetalInYears);
	System.out.println(" ");
	System.out.println("bracelet5 brand :"+bracelet5.brand);
	System.out.println("bracelet5 type:"+bracelet5.type);
	System.out.println("bracelet5 price:"+bracelet5.price);
	System.out.println("bracelet5 qualityInCarat:"+bracelet5.qualityInCarat);
	System.out.println("bracelet5 durabilityOfMetalInYears:"+bracelet5.durabilityOfMetalInYears);
	System.out.println(" ");
	
	
		Carom carom= new Carom();
		Carom carom1= new Carom("Synco");
		Carom carom2= new Carom("Surco","Standard Carrom");
		Carom carom3= new Carom("Precise", "Round Carrom", 950);
		Carom carom4= new Carom("GSI", "Professional Carrom",1500, "Wood");
		Carom carom5= new Carom("Siscaa", "Trick Shot Carrom",1200, "Fiber_Wood", 2);
		
	System.out.println(" ");	
	System.out.println("carom brand :"+carom.brand);
	System.out.println("carom type:"+carom.type);
	System.out.println("carom price:"+carom.price);
	System.out.println("carom madeOf:"+carom.madeOf);
	System.out.println("carom noOfstrikers:"+carom.noOfstrikers);
	System.out.println(" ");
	System.out.println("carom1 brand :"+carom1.brand);
	System.out.println("carom1 type:"+carom1.type);
	System.out.println("carom1 price:"+carom1.price);
	System.out.println("carom1 madeOf:"+carom1.madeOf);
	System.out.println("carom1 noOfstrikers:"+carom1.noOfstrikers);
	System.out.println(" ");
	System.out.println("carom2 brand :"+carom2.brand);
	System.out.println("carom2 type:"+carom2.type);
	System.out.println("carom2 price:"+carom2.price);
	System.out.println("carom2 madeOf:"+carom2.madeOf);
	System.out.println("carom2 noOfstrikers:"+carom2.noOfstrikers);
	System.out.println(" ");
	System.out.println("carom3 brand :"+carom3.brand);
	System.out.println("carom3 type:"+carom3.type);
	System.out.println("carom3 price:"+carom3.price);
	System.out.println("carom3 madeOf:"+carom3.madeOf);
	System.out.println("carom3 noOfstrikers:"+carom3.noOfstrikers);
	System.out.println(" ");
	System.out.println("carom4 brand :"+carom4.brand);
	System.out.println("carom4 type:"+carom4.type);
	System.out.println("carom4 price:"+carom4.price);
	System.out.println("carom4 madeOf:"+carom4.madeOf);
	System.out.println("carom4 noOfstrikers:"+carom4.noOfstrikers);
	System.out.println(" ");
	System.out.println("carom5 brand :"+carom5.brand);
	System.out.println("carom5 type:"+carom5.type);
	System.out.println("carom5 price:"+carom5.price);
	System.out.println("carom5 madeOf:"+carom5.madeOf);
	System.out.println("carom5 noOfstrikers:"+carom5.noOfstrikers);
	System.out.println(" ");
	}
}