class Runner{
	public static void main (String[] nnn){
		Keyboard keyboard= new Keyboard();
		Keyboard keyboard1= new Keyboard("Logitech");
		Keyboard keyboard2= new Keyboard("Microsoft",777);
		Keyboard keyboard3= new Keyboard("Corsair", 796, 71);
		Keyboard keyboard4= new Keyboard("Razer", 871,68, "Silver");
		Keyboard keyboard5= new Keyboard("Dell",1971,106,"Grey",1571);
		
		
	System.out.println(" ");	
	System.out.println("keyboard brand :"+keyboard.brand);
	System.out.println("keyboard color:"+keyboard.color);
	System.out.println("keyboard cost:"+keyboard.cost);
	System.out.println("keyboard noOfKeys:"+keyboard.noOfKeys);
	System.out.println("keyboard type:"+keyboard.type);
	System.out.println("keyboard serialNo :"+keyboard.serialNo);
	System.out.println(" ");
	System.out.println("keyboard1 brand :"+keyboard1.brand);
	System.out.println("keyboard1 color:"+keyboard1.color);
	System.out.println("keyboard1 cost:"+keyboard1.cost);
	System.out.println("keyboard1 noOfKeys:"+keyboard1.noOfKeys);
	System.out.println("keyboard1 type:"+keyboard1.type);
	System.out.println("keyboard1 serialNo :"+keyboard1.serialNo);
	System.out.println(" ");
	System.out.println("keyboard2 brand :"+keyboard2.brand);
	System.out.println("keyboard2 color:"+keyboard2.color);
	System.out.println("keyboard2 cost:"+keyboard2.cost);
	System.out.println("keyboard2 noOfKeys:"+keyboard2.noOfKeys);
	System.out.println("keyboard2 type:"+keyboard2.type);
	System.out.println("keyboard2 serialNo :"+keyboard2.serialNo);
	System.out.println(" ");
	System.out.println("keyboard3 brand :"+keyboard3.brand);
	System.out.println("keyboard3 color:"+keyboard3.color);
	System.out.println("keyboard3 cost:"+keyboard3.cost);
	System.out.println("keyboard3 noOfKeys:"+keyboard3.noOfKeys);
	System.out.println("keyboard3 type:"+keyboard3.type);
	System.out.println("keyboard3 serialNo :"+keyboard3.serialNo);
	System.out.println(" ");
	System.out.println("keyboard4 brand :"+keyboard4.brand);
	System.out.println("keyboard4 color:"+keyboard4.color);
	System.out.println("keyboard4 cost:"+keyboard4.cost);
	System.out.println("keyboard4 noOfKeys:"+keyboard4.noOfKeys);
	System.out.println("keyboard4 type:"+keyboard4.type);
	System.out.println("keyboard4 serialNo :"+keyboard4.serialNo);
	System.out.println(" ");
	System.out.println("keyboard5 brand :"+keyboard5.brand);
	System.out.println("keyboard5 color:"+keyboard5.color);
	System.out.println("keyboard5 cost:"+keyboard5.cost);
	System.out.println("keyboard5 noOfKeys:"+keyboard5.noOfKeys);
	System.out.println("keyboard5 type:"+keyboard5.type);
	System.out.println("keyboard5 serialNo :"+keyboard5.serialNo);
	System.out.println(" ");
	
	
	
		MatchBoxM matchbox= new MatchBoxM();
		MatchBoxM matchbox1= new MatchBoxM("Hot Wheels");
		MatchBoxM matchbox2= new MatchBoxM("Maisto",71);
		MatchBoxM matchbox3= new MatchBoxM("Tomica", 74, 5);
		MatchBoxM matchbox4= new MatchBoxM("Corgi", 84,7, 5);
		MatchBoxM matchbox5= new MatchBoxM("Majorette",150,6,4,"Medium");
		MatchBoxM matchbox6= new MatchBoxM("Siku",761,8,3,"Large",24);
	
	
	System.out.println(" ");
	System.out.println("matchbox brand :"+matchbox.brand);
	System.out.println("matchbox noOfSticks:"+matchbox.noOfSticks);
	System.out.println("matchbox lengthInCm:"+matchbox.lengthInCm);
	System.out.println("matchbox price:"+matchbox.price);
	System.out.println("matchbox size:"+matchbox.size);
	System.out.println("matchbox weightInGms :"+matchbox.weightInGms);
	System.out.println("matchbox type :"+matchbox.type);
	System.out.println(" ");
	System.out.println("matchbox1 brand :"+matchbox1.brand);
	System.out.println("matchbox1 noOfSticks:"+matchbox1.noOfSticks);
	System.out.println("matchbox1 lengthInCm:"+matchbox1.lengthInCm);
	System.out.println("matchbox1 price:"+matchbox1.price);
	System.out.println("matchbox1 size:"+matchbox1.size);
	System.out.println("matchbox1 weightInGms :"+matchbox1.weightInGms);
	System.out.println("matchbox1 type :"+matchbox1.type);
	System.out.println(" ");
	System.out.println("matchbox2 brand :"+matchbox2.brand);
	System.out.println("matchbox2 noOfSticks:"+matchbox2.noOfSticks);
	System.out.println("matchbox2 lengthInCm:"+matchbox2.lengthInCm);
	System.out.println("matchbox2 price:"+matchbox2.price);
	System.out.println("matchbox2 size:"+matchbox2.size);
	System.out.println("matchbox2 weightInGms :"+matchbox2.weightInGms);
	System.out.println("matchbox2 type :"+matchbox2.type);
	System.out.println(" ");
	System.out.println("matchbox3 brand :"+matchbox3.brand);
	System.out.println("matchbox3 noOfSticks:"+matchbox3.noOfSticks);
	System.out.println("matchbox3 lengthInCm:"+matchbox3.lengthInCm);
	System.out.println("matchbox3 price:"+matchbox3.price);
	System.out.println("matchbox3 size:"+matchbox3.size);
	System.out.println("matchbox3 weightInGms :"+matchbox3.weightInGms);
	System.out.println("matchbox3 type :"+matchbox3.type);
	System.out.println(" ");
	System.out.println("matchbox4 brand :"+matchbox4.brand);
	System.out.println("matchbox4 noOfSticks:"+matchbox4.noOfSticks);
	System.out.println("matchbox4 lengthInCm:"+matchbox4.lengthInCm);
	System.out.println("matchbox4 price:"+matchbox4.price);
	System.out.println("matchbox4 size:"+matchbox4.size);
	System.out.println("matchbox4 weightInGms :"+matchbox4.weightInGms);
	System.out.println("matchbox4 type :"+matchbox4.type);
	System.out.println(" ");
	System.out.println("matchbox5 brand :"+matchbox5.brand);
	System.out.println("matchbox5 noOfSticks:"+matchbox5.noOfSticks);
	System.out.println("matchbox5 lengthInCm:"+matchbox5.lengthInCm);
	System.out.println("matchbox5 price:"+matchbox5.price);
	System.out.println("matchbox5 size:"+matchbox5.size);
	System.out.println("matchbox5 weightInGms :"+matchbox5.weightInGms);
	System.out.println("matchbox5 type :"+matchbox5.type);
	System.out.println(" ");
	System.out.println("matchbox6 brand :"+matchbox6.brand);
	System.out.println("matchbox6 noOfSticks:"+matchbox6.noOfSticks);
	System.out.println("matchbox6 lengthInCm:"+matchbox6.lengthInCm);
	System.out.println("matchbox6 price:"+matchbox6.price);
	System.out.println("matchbox6 size:"+matchbox6.size);
	System.out.println("matchbox6 weightInGms :"+matchbox6.weightInGms);
	System.out.println("matchbox6 type :"+matchbox6.type);
	System.out.println(" ");
	
	
	
	ShowRoom showroom= new ShowRoom();
	ShowRoom showroom1= new ShowRoom("Mercedees");
	ShowRoom showroom2= new ShowRoom("BMW",17);
	ShowRoom showroom3= new ShowRoom("ROLESROYCE", 18, 5000);
	ShowRoom showroom4= new ShowRoom("TATA", 21,6000, 650000);
	ShowRoom showroom5= new ShowRoom("HardleyDavidson",24,7000,30000000,"Gujrat");
	ShowRoom showroom6= new ShowRoom("Maruthi",57,4000,450000,"Hydrabad",600000);
	ShowRoom showroom7= new ShowRoom("Mahendra",58,2000,250000,"Vishakapatnam",800000,51);
		
	System.out.println(" ");
	System.out.println("showroom name :"+showroom.name);
	System.out.println("showroom noOfBranches:"+showroom.noOfBranches);
	System.out.println("showroom noOfEmployees:"+showroom.noOfEmployees);
	System.out.println("showroom minPrice:"+showroom.minPrice);
	System.out.println("showroom maxPrice:"+showroom.maxPrice);
	System.out.println("showroom minSale :"+showroom.minSale);
	System.out.println("showroom type :"+showroom.type);
	System.out.println(" ");
	System.out.println("showroom1 name :"+showroom1.name);
	System.out.println("showroom1 noOfBranches:"+showroom1.noOfBranches);
	System.out.println("showroom1 noOfEmployees:"+showroom1.noOfEmployees);
	System.out.println("showroom1 minPrice:"+showroom1.minPrice);
	System.out.println("showroom1 maxPrice:"+showroom1.maxPrice);
	System.out.println("showroom1 minSale :"+showroom1.minSale);
	System.out.println("showroom1 type :"+showroom1.type);
	System.out.println(" ");
	System.out.println("showroom2 name :"+showroom2.name);
	System.out.println("showroom2 noOfBranches:"+showroom2.noOfBranches);
	System.out.println("showroom2 noOfEmployees:"+showroom2.noOfEmployees);
	System.out.println("showroom2 minPrice:"+showroom2.minPrice);
	System.out.println("showroom2 maxPrice:"+showroom2.maxPrice);
	System.out.println("showroom2 minSale :"+showroom2.minSale);
	System.out.println("showroom2 type :"+showroom2.type);
	System.out.println(" ");
	System.out.println("showroom3 name :"+showroom3.name);
	System.out.println("showroom3 noOfBranches:"+showroom3.noOfBranches);
	System.out.println("showroom3 noOfEmployees:"+showroom3.noOfEmployees);
	System.out.println("showroom3 minPrice:"+showroom3.minPrice);
	System.out.println("showroom3 maxPrice:"+showroom3.maxPrice);
	System.out.println("showroom3 minSale :"+showroom3.minSale);
	System.out.println("showroom3 type :"+showroom3.type);
	System.out.println(" ");
	System.out.println("showroom4 name :"+showroom4.name);
	System.out.println("showroom4 noOfBranches:"+showroom4.noOfBranches);
	System.out.println("showroom4 noOfEmployees:"+showroom4.noOfEmployees);
	System.out.println("showroom4 minPrice:"+showroom4.minPrice);
	System.out.println("showroom4 maxPrice:"+showroom4.maxPrice);
	System.out.println("showroom4 minSale :"+showroom4.minSale);
	System.out.println("showroom4 type :"+showroom4.type);
	System.out.println(" ");
	System.out.println("showroom5 name :"+showroom5.name);
	System.out.println("shoshowroom5wroom noOfBranches:"+showroom5.noOfBranches);
	System.out.println("showroom5 noOfEmployees:"+showroom5.noOfEmployees);
	System.out.println("showroom5 minPrice:"+showroom5.minPrice);
	System.out.println("showroom5 maxPrice:"+showroom5.maxPrice);
	System.out.println("showroom5 minSale :"+showroom5.minSale);
	System.out.println("showroom5 type :"+showroom5.type);
	System.out.println(" ");
	System.out.println("showroom6 name :"+showroom6.name);
	System.out.println("showroom6 noOfBranches:"+showroom6.noOfBranches);
	System.out.println("showroom6 noOfEmployees:"+showroom6.noOfEmployees);
	System.out.println("showroom6 minPrice:"+showroom6.minPrice);
	System.out.println("showroom6 maxPrice:"+showroom6.maxPrice);
	System.out.println("showroom6 minSale :"+showroom6.minSale);
	System.out.println("showroom6 type :"+showroom6.type);
	System.out.println(" ");
	System.out.println("showroom7 name :"+showroom7.name);
	System.out.println("showroom7 noOfBranches:"+showroom7.noOfBranches);
	System.out.println("showroom7 noOfEmployees:"+showroom7.noOfEmployees);
	System.out.println("showroom7 minPrice:"+showroom7.minPrice);
	System.out.println("showroom7 maxPrice:"+showroom7.maxPrice);
	System.out.println("showroom7 minSale :"+showroom7.minSale);
	System.out.println("showroom7 type :"+showroom7.type);
	}
}

